# Configuration for Rasa NLU and Core
version: "3.1"
recipe: default.v1
language: en

pipeline:
  # Tokenization
  - name: WhitespaceTokenizer
  
  # Featurizers
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  
  # Intent classification and entity extraction
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  
  # Entity processing
  - name: EntitySynonymMapper
  
  # Response selection (if using ResponseSelector)
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: faq
    constrain_similarities: true

  # Fallback for low confidence predictions
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  # Remember exact conversation patterns
  - name: MemoizationPolicy
  
  # Handle explicit rules
  - name: RulePolicy
  
  # Main dialogue policy
  - name: TEDPolicy
    epochs: 100
    constrain_similarities: true
  
  # Handle unexpected intent predictions
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100

assistant_id: placeholder
